x-spark-common: &spark-common
  build: .
  deploy:
    resources:
      limits:
        memory: 4G
        cpus: '2'
  volumes:
    - ./spark-warehouse:/opt/bitnami/spark/spark-warehouse

services:
  spark-master:
    <<: *spark-common
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'  # Web UI
      - '7077:7077'  # Spark master port

  spark-worker-1:
    <<: *spark-common
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master 

  spark-worker-2:
    <<: *spark-common
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master


  spark-connect:
    <<: *spark-common
    ports:
      - '15002:15002'  # Spark Connect port
      - '4040:4040'    # Spark Connect Web UI port
    environment:
      - SPARK_MODE=master
    depends_on:
      - spark-master 
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark-master:7077
      --class org.apache.spark.sql.connect.SimpleSparkConnectService
      --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
      --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog
      --conf spark.sql.catalog.spark_catalog.type=hive
      --conf spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.local.type=hadoop
      --conf spark.sql.catalog.local.warehouse=/opt/bitnami/spark/spark-warehouse
      --conf spark.sql.defaultCatalog=local
      --conf spark.connect.web.ui.enabled=true
      --conf spark.connect.web.ui.port=4040
      --conf spark.connect.web.ui.host=0.0.0.0
      --conf spark.connect.bindAddress=0.0.0.0
      --conf spark.connect.portEnv=15002
      spark-internal
      
  # spark-connect:
  #   <<: *spark-common
  #   ports:
  #     - '15002:15002'  # Spark Connect port
  #     - '9090:9090'    # Spark Connect Web UI port
  #   environment:
  #     - SPARK_MODE=master
  #   command: >
  #     /opt/bitnami/spark/bin/spark-submit
  #     --master spark://spark-master:7077
  #     --class org.apache.spark.sql.connect.SimpleSparkConnectService
  #     --packages org.apache.spark:spark-connect_2.12:3.5.5,io.delta:delta-core_2.12:2.4.0
  #     --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
  #     --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
  #     --conf spark.connect.web.ui.enabled=true
  #     --conf spark.connect.web.ui.port=9090
  #     --conf spark.connect.web.ui.host=0.0.0.0
  #     --conf spark.connect.bindAddress=0.0.0.0
  #     --conf spark.connect.portEnv=15002
  #     spark-internal